### ISSUE TITLE
Arm mac issue

### ISSUE THREAD

**Issue by nsemirdev** [gungorbasa/VIPER-Template#1]
<unknown>:0: remark: did not find a prebuilt standard library for target 'arm64-apple-macos' compatible with this Swift compiler; building it may take a few minutes, but it should only happen once for this combination of compiler and target
====================================
❌  Ooops! Something went wrong 😡 : The file doesn’t exist.
====================================

**Comment by gungorbasa** [comment]
It could be about Mac's permissions. First time I tried, I received the same error as well. Once I allow my terminal to make the changes in the privacy settings, it worked perfectly fine. 

Also, please make sure that you properly installed the Xcode and opened it before you run the script.

<img width="738" alt="Screenshot 2023-01-17 at 2 00 51 PM" src="https://user-images.githubusercontent.com/2487031/212882271-8515a971-9e9f-48af-8f15-812b1d26e567.png">
